In [2]:
import torch

In [30]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [31]:
#item  - > .item() extracts the lone value from a tensor that's been carefully crafted to contain just one element.  **work with only one element** 
scaler.item()


3

In [33]:
vector = torch.tensor([2,3,4,5,6])
vector

tensor([2, 3, 4, 5, 6])

In [40]:
#tolist()  -> coverts tensor to list
v=vector.tolist()
type(v)

list

In [44]:
matrix = torch.tensor([[2,3],
                       [4,5]])

In [51]:
print(matrix.ndim)
matrix.size() #shape()


2


torch.Size([2, 2])

In [55]:
tensor = torch.tensor([[[2,3],
                       [4,5]]])

In [57]:
print(tensor.ndim)
tensor.size() #shape()

3


torch.Size([1, 2, 2])

### Random tensors

In [61]:
random_tensor  = torch.rand(3,4)
random_tensor

tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162]])

In [63]:
random_tensor1  = torch.rand(2,3,3)
random_tensor1

tensor([[[0.8169, 0.3321, 0.1087],
         [0.0825, 0.5125, 0.7747],
         [0.9768, 0.4734, 0.0389]],

        [[0.2240, 0.9190, 0.6691],
         [0.9189, 0.0542, 0.1549],
         [0.2184, 0.5774, 0.8134]]])

### Zeros and Ones

In [64]:
zero_tensor = torch.zeros(size=(3, 3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [68]:
ones_tensor = torch.ones(size=(3, 3),dtype=torch.float16)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

### range / arange

In [73]:
torch.range(2,4) #deprecate

C:\Users\ASUS\AppData\Local\Temp\ipykernel_2772\3572756921.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2,4) #deprecate


tensor([2., 3., 4.])

In [76]:
torch.arange(2,6)

tensor([2, 3, 4, 5])

In [77]:
torch.arange(start=2 ,end=60, step=3)

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59])

### tensor like

In [89]:
print(torch.full_like(input = random_tensor , fill_value=6))
print(torch.rand_like(input = random_tensor))
print(torch.ones_like(input = random_tensor))
print(torch.zeros_like(input = random_tensor))
print(torch.empty_like(input = random_tensor))
print(torch.randn_like(input = random_tensor))




tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[0.0727, 0.5268, 0.1551, 0.1483],
        [0.9812, 0.0748, 0.9865, 0.1721],
        [0.5440, 0.2240, 0.4617, 0.1707]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[-0.6106,  1.2443,  0.3514, -0.3527],
        [ 0.8778,  0.5765,  1.2207, -1.8894],
        [-0.4040, -0.4633, -0.5185, -0.0408]])


### tensor dtypes

In [99]:
# default - > float32 for float & int64 for int

float_32 = torch.tensor([3.,4.,6.0])
int_64 = torch.tensor([3,4,6])
print(float_32.dtype)
print(int_64.dtype)


torch.float32
torch.int64


In [106]:
float_16 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float16,
                        device=torch.device('cpu'))
float_32 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float32)
float_64 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float64)

print(float_16.dtype)
print(float_32.dtype)
print(float_64.dtype)

torch.float16
torch.float32
torch.float64


In [108]:
float_16_converted = float_64.type(torch.float16)
float_16_converted.dtype

torch.float16

### tensor manipulation

In [113]:
# addition

print(torch.add(random_tensor,1))  # or print(random_tensor + 1)

#subtraction 

print(torch.sub(random_tensor,1))  # or print(random_tensor - 1)

# division

print(torch.div(random_tensor,1))  # or print(random_tensor / 1)

# scalar multiplication / element wise multiplication

print(torch.mul(random_tensor,1))  # or print(random_tensor * 1)




tensor([[1.5514, 1.4594, 1.3098, 1.8337],
        [1.7474, 1.8303, 1.5966, 1.7660],
        [1.8520, 1.7912, 1.3822, 1.2162]])
tensor([[-0.4486, -0.5406, -0.6902, -0.1663],
        [-0.2526, -0.1697, -0.4034, -0.2340],
        [-0.1480, -0.2088, -0.6178, -0.7838]])
tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162]])
tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162]])


In [121]:
# matrix multiplcation 
   # -> element wise multiplication
   # -> dotproduct
   
# -> element wise multiplication

print(torch.mul(random_tensor,random_tensor))  #print(random_tensor * random_tensor)


#  ->dot product

rand_tensor = random_tensor.T                   #3x4  4x3
print(torch.matmul(random_tensor,rand_tensor))  #or torch.mm()




tensor([[0.3040, 0.2110, 0.0960, 0.6950],
        [0.5586, 0.6894, 0.3559, 0.5867],
        [0.7260, 0.6259, 0.1461, 0.0467]])
tensor([[1.3060, 1.6169, 1.1318],
        [1.6169, 2.1907, 1.6873],
        [1.1318, 1.6873, 1.5447]])


In [122]:
rand_tensor

tensor([[0.5514, 0.7474, 0.8520],
        [0.4594, 0.8303, 0.7912],
        [0.3098, 0.5966, 0.3822],
        [0.8337, 0.7660, 0.2162]])

In [125]:
rand_tensor.reshape(3,4)

tensor([[0.5514, 0.7474, 0.8520, 0.4594],
        [0.8303, 0.7912, 0.3098, 0.5966],
        [0.3822, 0.8337, 0.7660, 0.2162]])

### tensor aggregation

In [127]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
print(torch.max(x))
print(torch.min(x))

tensor(9)
tensor(0)


In [137]:
#torch.mean(x.type(torch.int32)) -> ERROR

# torch.mean() work with only float datatype

torch.mean(x.type(torch.float64))

tensor(4.5000, dtype=torch.float64)

In [138]:
torch.sum(x)

tensor(45)

### position of min, max   ==> argmin ,agrmax

In [145]:
# return index

print(torch.argmin(x))
print(torch.argmax(x))
print(torch.argsort(x))
print(torch.argwhere(x))

tensor(0)
tensor(9)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
