In [2]:
import torch

In [30]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [31]:
#item  - > .item() extracts the lone value from a tensor that's been carefully crafted to contain just one element.  **work with only one element** 
scaler.item()


3

In [33]:
vector = torch.tensor([2,3,4,5,6])
vector

tensor([2, 3, 4, 5, 6])

In [40]:
#tolist()  -> coverts tensor to list
v=vector.tolist()
type(v)

list

In [44]:
matrix = torch.tensor([[2,3],
                       [4,5]])

In [51]:
print(matrix.ndim)
matrix.size() #shape()


2


torch.Size([2, 2])

In [55]:
tensor = torch.tensor([[[2,3],
                       [4,5]]])

In [57]:
print(tensor.ndim)
tensor.size() #shape()

3


torch.Size([1, 2, 2])

### Random tensors

In [61]:
random_tensor  = torch.rand(3,4)
random_tensor

tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162]])

In [63]:
random_tensor1  = torch.rand(2,3,3)
random_tensor1

tensor([[[0.8169, 0.3321, 0.1087],
         [0.0825, 0.5125, 0.7747],
         [0.9768, 0.4734, 0.0389]],

        [[0.2240, 0.9190, 0.6691],
         [0.9189, 0.0542, 0.1549],
         [0.2184, 0.5774, 0.8134]]])

### Zeros and Ones

In [64]:
zero_tensor = torch.zeros(size=(3, 3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [68]:
ones_tensor = torch.ones(size=(3, 3),dtype=torch.float16)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

### range / arange

In [73]:
torch.range(2,4) #deprecate

C:\Users\ASUS\AppData\Local\Temp\ipykernel_2772\3572756921.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2,4) #deprecate


tensor([2., 3., 4.])

In [76]:
torch.arange(2,6)

tensor([2, 3, 4, 5])

In [77]:
torch.arange(start=2 ,end=60, step=3)

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59])

### tensor like

In [89]:
print(torch.full_like(input = random_tensor , fill_value=6))
print(torch.rand_like(input = random_tensor))
print(torch.ones_like(input = random_tensor))
print(torch.zeros_like(input = random_tensor))
print(torch.empty_like(input = random_tensor))
print(torch.randn_like(input = random_tensor))




tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[0.0727, 0.5268, 0.1551, 0.1483],
        [0.9812, 0.0748, 0.9865, 0.1721],
        [0.5440, 0.2240, 0.4617, 0.1707]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[-0.6106,  1.2443,  0.3514, -0.3527],
        [ 0.8778,  0.5765,  1.2207, -1.8894],
        [-0.4040, -0.4633, -0.5185, -0.0408]])


### tensor dtypes

In [99]:
# default - > float32 for float & int64 for int

float_32 = torch.tensor([3.,4.,6.0])
int_64 = torch.tensor([3,4,6])
print(float_32.dtype)
print(int_64.dtype)


torch.float32
torch.int64


In [106]:
float_16 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float16,
                        device=torch.device('cpu'))
float_32 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float32)
float_64 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float64)

print(float_16.dtype)
print(float_32.dtype)
print(float_64.dtype)

torch.float16
torch.float32
torch.float64


In [108]:
float_16_converted = float_64.type(torch.float16)
float_16_converted.dtype

torch.float16

### tensor manipulation

In [113]:
# addition

print(torch.add(random_tensor,1))  # or print(random_tensor + 1)

#subtraction 

print(torch.sub(random_tensor,1))  # or print(random_tensor - 1)

# division

print(torch.div(random_tensor,1))  # or print(random_tensor / 1)

# scalar multiplication / element wise multiplication

print(torch.mul(random_tensor,1))  # or print(random_tensor * 1)




tensor([[1.5514, 1.4594, 1.3098, 1.8337],
        [1.7474, 1.8303, 1.5966, 1.7660],
        [1.8520, 1.7912, 1.3822, 1.2162]])
tensor([[-0.4486, -0.5406, -0.6902, -0.1663],
        [-0.2526, -0.1697, -0.4034, -0.2340],
        [-0.1480, -0.2088, -0.6178, -0.7838]])
tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162]])
tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162]])


In [121]:
# matrix multiplcation 
   # -> element wise multiplication
   # -> dotproduct
   
# -> element wise multiplication

print(torch.mul(random_tensor,random_tensor))  #print(random_tensor * random_tensor)


#  ->dot product

rand_tensor = random_tensor.T                   #3x4  4x3
print(torch.matmul(random_tensor,rand_tensor))  #or torch.mm()




tensor([[0.3040, 0.2110, 0.0960, 0.6950],
        [0.5586, 0.6894, 0.3559, 0.5867],
        [0.7260, 0.6259, 0.1461, 0.0467]])
tensor([[1.3060, 1.6169, 1.1318],
        [1.6169, 2.1907, 1.6873],
        [1.1318, 1.6873, 1.5447]])


In [122]:
rand_tensor

tensor([[0.5514, 0.7474, 0.8520],
        [0.4594, 0.8303, 0.7912],
        [0.3098, 0.5966, 0.3822],
        [0.8337, 0.7660, 0.2162]])

In [125]:
rand_tensor.reshape(3,4)

tensor([[0.5514, 0.7474, 0.8520, 0.4594],
        [0.8303, 0.7912, 0.3098, 0.5966],
        [0.3822, 0.8337, 0.7660, 0.2162]])

#### tensor aggregation

In [127]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
print(torch.max(x))
print(torch.min(x))

tensor(9)
tensor(0)


In [137]:
#torch.mean(x.type(torch.int32)) -> ERROR

# torch.mean() work with only float datatype

torch.mean(x.type(torch.float64))

tensor(4.5000, dtype=torch.float64)

In [138]:
torch.sum(x)

tensor(45)

#### position of min, max   ==> argmin ,agrmax

In [145]:
# return index

print(torch.argmin(x))
print(torch.argmax(x))
print(torch.argsort(x))
print(torch.argwhere(x))

tensor(0)
tensor(9)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


#### reshaping , stacking , squeezing , unsqueezing , tensors 

In [151]:
# Reshaping  or View
reshaped_tensor = random_tensor.reshape(2, 6)  
print("Reshaped Tensor:\n", reshaped_tensor)


#view
reshaped_tensor = random_tensor.view(6, 2)  
print("Reshaped Tensor:\n", reshaped_tensor)

# Stacking
stacked_tensor = torch.stack([random_tensor, random_tensor], dim=0)
print("Stacked Tensor:\n", stacked_tensor)

# hstack

stacked_tensor = torch.hstack([random_tensor, random_tensor])
print("horizatally stacked Tensor:\n", stacked_tensor)

#vsatck

stacked_tensor = torch.vstack([random_tensor, random_tensor])
print("vertically stacked Tensor:\n", stacked_tensor)

# Squeezing
squeezed_tensor = tensor.squeeze()
print("Squeezed Tensor:\n", squeezed_tensor)

# Unsqueezing
unsqueezed_tensor = tensor.unsqueeze(0)    #-> dimentions value
print("Unsqueezed Tensor:\n", unsqueezed_tensor)

Reshaped Tensor:
 tensor([[0.5514, 0.4594, 0.3098, 0.8337, 0.7474, 0.8303],
        [0.5966, 0.7660, 0.8520, 0.7912, 0.3822, 0.2162]])
Reshaped Tensor:
 tensor([[0.5514, 0.4594],
        [0.3098, 0.8337],
        [0.7474, 0.8303],
        [0.5966, 0.7660],
        [0.8520, 0.7912],
        [0.3822, 0.2162]])
Stacked Tensor:
 tensor([[[0.5514, 0.4594, 0.3098, 0.8337],
         [0.7474, 0.8303, 0.5966, 0.7660],
         [0.8520, 0.7912, 0.3822, 0.2162]],

        [[0.5514, 0.4594, 0.3098, 0.8337],
         [0.7474, 0.8303, 0.5966, 0.7660],
         [0.8520, 0.7912, 0.3822, 0.2162]]])
horizatally stacked Tensor:
 tensor([[0.5514, 0.4594, 0.3098, 0.8337, 0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660, 0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162, 0.8520, 0.7912, 0.3822, 0.2162]])
vertically stacked Tensor:
 tensor([[0.5514, 0.4594, 0.3098, 0.8337],
        [0.7474, 0.8303, 0.5966, 0.7660],
        [0.8520, 0.7912, 0.3822, 0.2162],
     

In [158]:
# torch.permute  -> rearranges the dimentions

x = torch.rand(size=(255,255,3))
print(x.shape)
x_permute = torch.permute(x,(2,1,0))
print(x_permute.shape)

torch.Size([255, 255, 3])
torch.Size([3, 255, 255])


In [159]:
x

tensor([[[0.0652, 0.2087, 0.7798],
         [0.2118, 0.7521, 0.6565],
         [0.7503, 0.2111, 0.2311],
         ...,
         [0.4871, 0.4211, 0.4690],
         [0.2308, 0.8311, 0.8363],
         [0.6798, 0.6956, 0.8648]],

        [[0.2166, 0.7683, 0.3343],
         [0.9050, 0.3830, 0.9554],
         [0.9764, 0.5714, 0.5163],
         ...,
         [0.6984, 0.9035, 0.4730],
         [0.7156, 0.8266, 0.7465],
         [0.3788, 0.2924, 0.3780]],

        [[0.0160, 0.7923, 0.9683],
         [0.2221, 0.6460, 0.9257],
         [0.2211, 0.6041, 0.4555],
         ...,
         [0.9768, 0.2683, 0.6444],
         [0.6635, 0.7270, 0.9887],
         [0.7842, 0.3451, 0.5363]],

        ...,

        [[0.3569, 0.7194, 0.5843],
         [0.9328, 0.3427, 0.3881],
         [0.4043, 0.2811, 0.8405],
         ...,
         [0.4194, 0.6556, 0.1070],
         [0.2222, 0.5260, 0.1580],
         [0.0016, 0.0076, 0.2481]],

        [[0.7646, 0.0195, 0.9598],
         [0.6362, 0.1219, 0.9529],
         [0.

In [160]:
x_permute

tensor([[[0.0652, 0.2166, 0.0160,  ..., 0.3569, 0.7646, 0.2217],
         [0.2118, 0.9050, 0.2221,  ..., 0.9328, 0.6362, 0.7641],
         [0.7503, 0.9764, 0.2211,  ..., 0.4043, 0.5867, 0.9509],
         ...,
         [0.4871, 0.6984, 0.9768,  ..., 0.4194, 0.0142, 0.8931],
         [0.2308, 0.7156, 0.6635,  ..., 0.2222, 0.7471, 0.0066],
         [0.6798, 0.3788, 0.7842,  ..., 0.0016, 0.8247, 0.9997]],

        [[0.2087, 0.7683, 0.7923,  ..., 0.7194, 0.0195, 0.6326],
         [0.7521, 0.3830, 0.6460,  ..., 0.3427, 0.1219, 0.3769],
         [0.2111, 0.5714, 0.6041,  ..., 0.2811, 0.7371, 0.1897],
         ...,
         [0.4211, 0.9035, 0.2683,  ..., 0.6556, 0.4538, 0.7150],
         [0.8311, 0.8266, 0.7270,  ..., 0.5260, 0.1226, 0.8486],
         [0.6956, 0.2924, 0.3451,  ..., 0.0076, 0.7633, 0.4255]],

        [[0.7798, 0.3343, 0.9683,  ..., 0.5843, 0.9598, 0.7698],
         [0.6565, 0.9554, 0.9257,  ..., 0.3881, 0.9529, 0.6540],
         [0.2311, 0.5163, 0.4555,  ..., 0.8405, 0.6594, 0.

### indexing

In [177]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [184]:
print(x),print(x[0]),print(x[0][0]),print(x[0][0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


(None, None, None, None)

In [193]:
print(x[:, : ,:]) , print(x[0,:,:]),print(x[:,2 ,:]),print(x[:, : ,2]),print(x[: ,:]),print(x[0,:])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[7, 8, 9]])
tensor([[3, 6, 9]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


(None, None, None, None, None, None)

## PyTorch Tensors & Numpy

In [194]:
import numpy as np

In [202]:
np_array = np.arange(1,9)
torch_tensor = torch.arange(1,9)
print(type(np_array))
print(type(torch_tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [205]:
numpy_to_torch = torch.from_numpy(np_array)
print(numpy_to_torch),print(type(numpy_to_torch))
torch_to_numpy = torch_tensor.numpy()
print(torch_to_numpy),print(type(torch_to_numpy))

tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)
<class 'torch.Tensor'>
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


(None, None)