In [1]:
import torch

In [2]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [3]:
#item  - > .item() extracts the lone value from a tensor that's been carefully crafted to contain just one element.  **work with only one element** 
scaler.item()


3

In [4]:
vector = torch.tensor([2,3,4,5,6])
vector

tensor([2, 3, 4, 5, 6])

In [5]:
#tolist()  -> coverts tensor to list
v=vector.tolist()
type(v)

list

In [6]:
matrix = torch.tensor([[2,3],
                       [4,5]])

In [7]:
print(matrix.ndim)
matrix.size() #shape()


2


torch.Size([2, 2])

In [8]:
tensor = torch.tensor([[[2,3],
                       [4,5]]])

In [9]:
print(tensor.ndim)
tensor.size() #shape()

3


torch.Size([1, 2, 2])

### Random tensors

In [10]:
random_tensor  = torch.rand(3,4)
random_tensor

tensor([[0.5238, 0.7830, 0.2393, 0.9123],
        [0.4731, 0.0652, 0.8316, 0.2804],
        [0.5082, 0.1267, 0.3241, 0.3135]])

In [11]:
random_tensor1  = torch.rand(2,3,3)
random_tensor1

tensor([[[0.2456, 0.8886, 0.6514],
         [0.0866, 0.0934, 0.0594],
         [0.0945, 0.4121, 0.2575]],

        [[0.0424, 0.5666, 0.1466],
         [0.8939, 0.0759, 0.5763],
         [0.9066, 0.3876, 0.9839]]])

### Zeros and Ones

In [12]:
zero_tensor = torch.zeros(size=(3, 3))
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
ones_tensor = torch.ones(size=(3, 3),dtype=torch.float16)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

### range / arange

In [14]:
torch.range(2,4) #deprecate

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12716\3572756921.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2,4) #deprecate


tensor([2., 3., 4.])

In [15]:
torch.arange(2,6)

tensor([2, 3, 4, 5])

In [16]:
torch.arange(start=2 ,end=60, step=3)

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
        56, 59])

### tensor like

In [17]:
print(torch.full_like(input = random_tensor , fill_value=6))
print(torch.rand_like(input = random_tensor))
print(torch.ones_like(input = random_tensor))
print(torch.zeros_like(input = random_tensor))
print(torch.empty_like(input = random_tensor))
print(torch.randn_like(input = random_tensor))




tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[0.0386, 0.9526, 0.6290, 0.3094],
        [0.8372, 0.2434, 0.8681, 0.2025],
        [0.9679, 0.4669, 0.1773, 0.3758]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[ 1.4597,  1.5285,  1.4092, -0.5315],
        [ 1.1792, -1.6145,  0.5408, -1.1141],
        [-0.8113, -1.0798,  1.5655, -0.5306]])


### tensor dtypes

In [18]:
# default - > float32 for float & int64 for int

float_32 = torch.tensor([3.,4.,6.0])
int_64 = torch.tensor([3,4,6])
print(float_32.dtype)
print(int_64.dtype)


torch.float32
torch.int64


In [19]:
float_16 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float16,
                        device=torch.device('cpu'))
float_32 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float32)
float_64 = torch.tensor([3.,4.,6.0],
                        dtype=torch.float64)

print(float_16.dtype)
print(float_32.dtype)
print(float_64.dtype)

torch.float16
torch.float32
torch.float64


In [20]:
float_16_converted = float_64.type(torch.float16)
float_16_converted.dtype

torch.float16

### tensor manipulation

In [21]:
# addition

print(torch.add(random_tensor,1))  # or print(random_tensor + 1)

#subtraction 

print(torch.sub(random_tensor,1))  # or print(random_tensor - 1)

# division

print(torch.div(random_tensor,1))  # or print(random_tensor / 1)

# scalar multiplication / element wise multiplication

print(torch.mul(random_tensor,1))  # or print(random_tensor * 1)




tensor([[1.5238, 1.7830, 1.2393, 1.9123],
        [1.4731, 1.0652, 1.8316, 1.2804],
        [1.5082, 1.1267, 1.3241, 1.3135]])
tensor([[-0.4762, -0.2170, -0.7607, -0.0877],
        [-0.5269, -0.9348, -0.1684, -0.7196],
        [-0.4918, -0.8733, -0.6759, -0.6865]])
tensor([[0.5238, 0.7830, 0.2393, 0.9123],
        [0.4731, 0.0652, 0.8316, 0.2804],
        [0.5082, 0.1267, 0.3241, 0.3135]])
tensor([[0.5238, 0.7830, 0.2393, 0.9123],
        [0.4731, 0.0652, 0.8316, 0.2804],
        [0.5082, 0.1267, 0.3241, 0.3135]])


In [22]:
# matrix multiplcation 
   # -> element wise multiplication
   # -> dotproduct
   
# -> element wise multiplication

print(torch.mul(random_tensor,random_tensor))  #print(random_tensor * random_tensor)


#  ->dot product

rand_tensor = random_tensor.T                   #3x4  4x3
print(torch.matmul(random_tensor,rand_tensor))  #or torch.mm()




tensor([[0.2744, 0.6131, 0.0573, 0.8323],
        [0.2238, 0.0042, 0.6916, 0.0786],
        [0.2583, 0.0161, 0.1050, 0.0983]])
tensor([[1.7770, 0.7537, 0.7290],
        [0.7537, 0.9984, 0.6061],
        [0.7290, 0.6061, 0.4777]])


In [23]:
rand_tensor

tensor([[0.5238, 0.4731, 0.5082],
        [0.7830, 0.0652, 0.1267],
        [0.2393, 0.8316, 0.3241],
        [0.9123, 0.2804, 0.3135]])

In [24]:
rand_tensor.reshape(3,4)

tensor([[0.5238, 0.4731, 0.5082, 0.7830],
        [0.0652, 0.1267, 0.2393, 0.8316],
        [0.3241, 0.9123, 0.2804, 0.3135]])

#### tensor aggregation

In [25]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
print(torch.max(x))
print(torch.min(x))

tensor(9)
tensor(0)


In [27]:
#torch.mean(x.type(torch.int32)) -> ERROR

# torch.mean() work with only float datatype

torch.mean(x.type(torch.float64))

tensor(4.5000, dtype=torch.float64)

In [28]:
torch.sum(x)

tensor(45)

#### position of min, max   ==> argmin ,agrmax

In [29]:
# return index

print(torch.argmin(x))
print(torch.argmax(x))
print(torch.argsort(x))
print(torch.argwhere(x))

tensor(0)
tensor(9)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


#### reshaping , stacking , squeezing , unsqueezing , tensors 

In [30]:
# Reshaping  or View
reshaped_tensor = random_tensor.reshape(2, 6)  
print("Reshaped Tensor:\n", reshaped_tensor)


#view
reshaped_tensor = random_tensor.view(6, 2)  
print("Reshaped Tensor:\n", reshaped_tensor)

# Stacking
stacked_tensor = torch.stack([random_tensor, random_tensor], dim=0)
print("Stacked Tensor:\n", stacked_tensor)

# hstack

stacked_tensor = torch.hstack([random_tensor, random_tensor])
print("horizatally stacked Tensor:\n", stacked_tensor)

#vsatck

stacked_tensor = torch.vstack([random_tensor, random_tensor])
print("vertically stacked Tensor:\n", stacked_tensor)

# Squeezing
squeezed_tensor = tensor.squeeze()
print("Squeezed Tensor:\n", squeezed_tensor)

# Unsqueezing
unsqueezed_tensor = tensor.unsqueeze(0)    #-> dimentions value
print("Unsqueezed Tensor:\n", unsqueezed_tensor)

Reshaped Tensor:
 tensor([[0.5238, 0.7830, 0.2393, 0.9123, 0.4731, 0.0652],
        [0.8316, 0.2804, 0.5082, 0.1267, 0.3241, 0.3135]])
Reshaped Tensor:
 tensor([[0.5238, 0.7830],
        [0.2393, 0.9123],
        [0.4731, 0.0652],
        [0.8316, 0.2804],
        [0.5082, 0.1267],
        [0.3241, 0.3135]])
Stacked Tensor:
 tensor([[[0.5238, 0.7830, 0.2393, 0.9123],
         [0.4731, 0.0652, 0.8316, 0.2804],
         [0.5082, 0.1267, 0.3241, 0.3135]],

        [[0.5238, 0.7830, 0.2393, 0.9123],
         [0.4731, 0.0652, 0.8316, 0.2804],
         [0.5082, 0.1267, 0.3241, 0.3135]]])
horizatally stacked Tensor:
 tensor([[0.5238, 0.7830, 0.2393, 0.9123, 0.5238, 0.7830, 0.2393, 0.9123],
        [0.4731, 0.0652, 0.8316, 0.2804, 0.4731, 0.0652, 0.8316, 0.2804],
        [0.5082, 0.1267, 0.3241, 0.3135, 0.5082, 0.1267, 0.3241, 0.3135]])
vertically stacked Tensor:
 tensor([[0.5238, 0.7830, 0.2393, 0.9123],
        [0.4731, 0.0652, 0.8316, 0.2804],
        [0.5082, 0.1267, 0.3241, 0.3135],
     

In [31]:
# torch.permute  -> rearranges the dimentions

x = torch.rand(size=(255,255,3))
print(x.shape)
x_permute = torch.permute(x,(2,1,0))
print(x_permute.shape)

torch.Size([255, 255, 3])
torch.Size([3, 255, 255])


In [32]:
x

tensor([[[0.8881, 0.3275, 0.0309],
         [0.8575, 0.9414, 0.3046],
         [0.2420, 0.8888, 0.5031],
         ...,
         [0.6924, 0.5509, 0.0486],
         [0.6934, 0.6818, 0.0792],
         [0.8069, 0.2557, 0.7185]],

        [[0.5213, 0.7327, 0.8036],
         [0.0156, 0.0901, 0.6348],
         [0.6727, 0.7364, 0.9314],
         ...,
         [0.0053, 0.4183, 0.6608],
         [0.4508, 0.9788, 0.3893],
         [0.0886, 0.7938, 0.1247]],

        [[0.2100, 0.8965, 0.0126],
         [0.3618, 0.7577, 0.9236],
         [0.2550, 0.9728, 0.0634],
         ...,
         [0.5554, 0.7837, 0.9660],
         [0.7131, 0.7051, 0.3546],
         [0.6868, 0.1219, 0.0959]],

        ...,

        [[0.0684, 0.6627, 0.0125],
         [0.8071, 0.8139, 0.5667],
         [0.9781, 0.8356, 0.5183],
         ...,
         [0.6716, 0.0497, 0.8707],
         [0.6374, 0.9216, 0.4492],
         [0.1015, 0.7556, 0.3058]],

        [[0.8685, 0.5102, 0.0331],
         [0.4859, 0.1243, 0.4471],
         [0.

In [33]:
x_permute

tensor([[[0.8881, 0.5213, 0.2100,  ..., 0.0684, 0.8685, 0.6693],
         [0.8575, 0.0156, 0.3618,  ..., 0.8071, 0.4859, 0.8651],
         [0.2420, 0.6727, 0.2550,  ..., 0.9781, 0.9422, 0.5086],
         ...,
         [0.6924, 0.0053, 0.5554,  ..., 0.6716, 0.0612, 0.7814],
         [0.6934, 0.4508, 0.7131,  ..., 0.6374, 0.5618, 0.9454],
         [0.8069, 0.0886, 0.6868,  ..., 0.1015, 0.6141, 0.1649]],

        [[0.3275, 0.7327, 0.8965,  ..., 0.6627, 0.5102, 0.7241],
         [0.9414, 0.0901, 0.7577,  ..., 0.8139, 0.1243, 0.8887],
         [0.8888, 0.7364, 0.9728,  ..., 0.8356, 0.8123, 0.1524],
         ...,
         [0.5509, 0.4183, 0.7837,  ..., 0.0497, 0.6983, 0.7153],
         [0.6818, 0.9788, 0.7051,  ..., 0.9216, 0.4875, 0.7094],
         [0.2557, 0.7938, 0.1219,  ..., 0.7556, 0.3408, 0.7846]],

        [[0.0309, 0.8036, 0.0126,  ..., 0.0125, 0.0331, 0.7180],
         [0.3046, 0.6348, 0.9236,  ..., 0.5667, 0.4471, 0.0111],
         [0.5031, 0.9314, 0.0634,  ..., 0.5183, 0.4631, 0.

### indexing

In [34]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [35]:
print(x),print(x[0]),print(x[0][0]),print(x[0][0][0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


(None, None, None, None)

In [36]:
print(x[:, : ,:]) , print(x[0,:,:]),print(x[:,2 ,:]),print(x[:, : ,2]),print(x[: ,:]),print(x[0,:])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[7, 8, 9]])
tensor([[3, 6, 9]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


(None, None, None, None, None, None)

## PyTorch Tensors & Numpy

In [37]:
import numpy as np

In [38]:
np_array = np.arange(1,9)
torch_tensor = torch.arange(1,9)
print(type(np_array))
print(type(torch_tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [39]:
numpy_to_torch = torch.from_numpy(np_array)
print(numpy_to_torch),print(type(numpy_to_torch))
torch_to_numpy = torch_tensor.numpy()
print(torch_to_numpy),print(type(torch_to_numpy))

tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32)
<class 'torch.Tensor'>
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


(None, None)

In [40]:
import torch

# Set random seed for reproducibility
torch.manual_seed(42)
A = torch.rand(size=(3,4))
print(A)

torch.manual_seed(42)
B = torch.rand(size=(3,4))
print(B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


### GPU

In [44]:
torch.cuda.is_available()

False

device agnostic code

In [49]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [53]:
x = torch.arange(1,9)
x.device

device(type='cpu')

In [57]:
x.to(device=device)


tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
# numpy dont work on GPUs
# if tensor on GPU cant transform it into Numpy

In [61]:
tensor_on_cpu = x.cpu().numpy()
tensor_on_cpu

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)